apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: arcgis
  region: us-east-1

managedNodeGroups:
  - name: arcgis-mng
    instanceType: m6a.4xlarge
    minSize: 1
    maxSize: 2
    desiredCapacity: 1
