apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: arcgis
  region: us-east-1
  version: '1.27'

#vpc:
  #subnets:
    #private:
    #public:
      #us-east-1a:
        #id: "$subnet1"
      #us-east-1b:
        #id: "$subnet2"

managedNodeGroups:
  - name: arcgis-mng
    instanceType: m6a.4xlarge
    minSize: 1
    maxSize: 2
    desiredCapacity: 1
    #privateNetworking: true
