apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: arcgis-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  csi.storage.k8s.io/fstype: ext4
  type: gp3
reclaimPolicy: Delete
allowVolumeExpansion: true
